.TH "twapake" 1 "06/30/2012" "Frederic Galusik"


.SH NAME

.P
twapake \- A simple perl tool to manage last installed packages and to
keep a log of packages installed date

.SH SYNOPSIS

.P
\fBtwapake\fR [\fIOPTIONS\fR]

.SH DESCRIPTION

.P
\fBTwapake\fR is a system administration utility for Slackware
and Slackware based operating systems only, making easier the management
of last installed packages and making easier seeing the installation
date of a package.

.SH GENERAL OPTIONS

.TP
\fB\-h\fR, \fB\-\-help\fR
Simple help

.TP
\fB\-v\fR, \fB\-\-version\fR
Print Twapake version

.TP
\fB\-l\fR, \fB\-\-logfile\fR
Print a snapshot logfile to the /var/log/twapake/ directory.
A snapshot is a list of all packages sorted by installed date at T time.
The installed date is printed too, making easier to see when a package
has been installed on your system.

.TP
\fB\-i\fR, \fB\-\-installed\fR
Print a simple sorted list of installed packages to STDOUT

.TP
\fB\-n\fR, \fB\-\-nlpkg\fR
Used with \fB\-i\fR. Let you choose how many \fBN\fR last installed packages
you want to print to STDOUT

.TP
\fB\-r\fR, \fB\-\-remove\fR
Remove the last \fBN\fR installed packages

.TP
\fB\-s\fR, \fB\-\-since\fR
Print today installed packages to STDOUT

.TP
\fB\-c\fR, \fB\-\-choosedate\fR
Used with \fB\-s\fR. Print packages installed since this choosen date

.TP
\fB\-u\fR, \fB\-\-ui\fR
Launch the Curses User Interface for an easier removal. You can choose
the packages you want to remove in a list sorted by installed date

.SH COMMAND LINE USAGE

.P
Here are some usages examples:

.TP
\fBtwapake \-i \-n 10\fR
Print the 10 last installed packages to STDOUT

.TP
\fBtwapake \-r \-n 5\fR
Show you the last 5 installed packages and ask you if you want to remove
them

.TP
\fBtwapake \-s \-c 2011\-05\-25\fR
Show you the packages installed on your system since the 2011\-05\-25

.SH THE CURSES INTERFACE

.P
Within the program you can use the following keys.

.TP
\fBUP / DOWN\fR
Navigate the packages list

.TP
\fBSPACE\fR
Select/Unselect a package

.TP
\fBCtrl\-X\fR
Show you the menu

.TP
\fBCtrl\-U\fR
Unselect all choosen packages

.TP
\fBCtrl\-R\fR
Remove all selected packages

.TP
\fBCtrl\-Q\fR
Quit Twapake

.SH WEBSITE

.P
http://www.salixos.org/wiki/index.php/Twapake

.SH AUTHOR

.P
Twapake was written by Frederic Galusik <fredg~at~salixos~dot~org>

.SH SEE ALSO

.P
\fBpkgtool\fR(8), \fBremovepkg\fR(8), \fBspkg\fR(8)

.\" man code generated by txt2tags 2.6 (http://txt2tags.org)
.\" cmdline: txt2tags twapake.t2t
